"""Module: inventory/routes_delivery.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, request, jsonify
from flask_login import login_required
from decimal import Decimal

try:
    from erp.extensions import db
    from erp.inventory.valuation import post_sle
    from erp.inventory.models import Delivery
except Exception as e:
    db = None
    post_sle = None
    Delivery = None

inventory_delivery_bp = Blueprint("inventory_delivery", __name__, url_prefix="/inventory")

@inventory_delivery_bp.route("/delivery", methods=["POST"])
@login_required
def create_delivery():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    if db is None or post_sle is None:
        return jsonify({"error": "Inventory ledger not available"}), 500
    data = request.get_json(silent=True) or {}
    delivery_id = None
    if Delivery is not None:
        d = Delivery(customer_id=data.get("customer_id"))
        db.session.add(d); db.session.flush()
        delivery_id = d.id
    for ln in data.get("lines", []):
        qty = Decimal(str(ln.get("qty", 0)))
        if qty > 0:
            qty = -qty  # issues are negative
        post_sle(item_id=ln["item_id"],
                 warehouse_id=ln["warehouse_id"],
                 qty=qty,
                 voucher_type="Delivery",
                 voucher_id=delivery_id,
                 lot_id=ln.get("lot_id"))
    db.session.commit()
    return jsonify({"id": str(delivery_id) if delivery_id else None}), 201



