"""Module: models/order.py — audit-added docstring. Refine with precise purpose when convenient."""
from __future__ import annotations
from datetime import UTC, datetime
from decimal import Decimal
from typing import Iterable

from erp.models import db

class Order(db.Model):
    __tablename__ = "orders"

    id = db.Column(db.Integer, primary_key=True)

    # Likely relations used in tests
    organization_id = db.Column(
        db.Integer,
        db.ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    status = db.Column(db.String(20), nullable=False, default="submitted")  # submitted->approved->invoiced->delivered->settled
    payment_status = db.Column(
        db.String(20), nullable=False, default="unpaid", server_default="unpaid"
    )  # unpaid|partial|settled
    currency = db.Column(db.String(8), nullable=False, default="USD")
    total_amount = db.Column(db.Numeric(12, 2), nullable=False, default=Decimal("0.00"))

    initiator_type = db.Column(db.String(20), nullable=True)  # client|employee|management
    initiator_id = db.Column(db.Integer, nullable=True)
    assigned_sales_rep_id = db.Column(
        db.Integer, db.ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )
    commission_enabled = db.Column(db.Boolean, nullable=False, default=False, server_default=db.text("false"))
    commission_rate = db.Column(
        db.Numeric(5, 4), nullable=False, default=Decimal("0.02"), server_default=db.text("0.02")
    )
    commission_status = db.Column(
        db.String(20), nullable=False, default="none", server_default="none"
    )  # none|pending|eligible|paid|blocked
    commission_approved_by_management = db.Column(
        db.Boolean, nullable=False, default=False, server_default=db.text("false")
    )
    commission_block_reason = db.Column(db.String(255), nullable=True)

    geo_lat = db.Column(db.Float, nullable=True)
    geo_lng = db.Column(db.Float, nullable=True)
    geo_accuracy_m = db.Column(db.Float, nullable=True)
    geo_recorded_by_id = db.Column(
        db.Integer, db.ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True
    )
    geo_recorded_at = db.Column(db.DateTime(timezone=True), nullable=True)

    placed_at = db.Column(db.DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC))
    paid_at = db.Column(db.DateTime(timezone=True), nullable=True)
    shipped_at = db.Column(db.DateTime(timezone=True), nullable=True)

    created_at = db.Column(db.DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC))
    updated_at = db.Column(
        db.DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )

    organization = db.relationship(
        "Organization",
        backref=db.backref("orders", lazy=True, cascade="all, delete-orphan"),
        foreign_keys=[organization_id],
    )
    user = db.relationship(
        "User",
        backref=db.backref("orders", lazy=True),
        foreign_keys=[user_id],
    )
    assigned_sales_rep = db.relationship(
        "User",
        backref=db.backref("assigned_orders", lazy=True),
        foreign_keys=[assigned_sales_rep_id],
    )
    geo_recorded_by = db.relationship(
        "User",
        foreign_keys=[geo_recorded_by_id],
        backref=db.backref("orders_geo_recorded", lazy=True),
    )

    # handy helpers
    def mark_paid(self):
        """Autogenerated docstring (audit). Describe purpose, params, and return value."""
        self.status = "paid"
        self.paid_at = datetime.now(UTC)
        self.payment_status = "settled"
        self._sync_commission_status()

    def mark_shipped(self):
        """Autogenerated docstring (audit). Describe purpose, params, and return value."""
        self.status = "shipped"
        self.shipped_at = datetime.now(UTC)

    def set_status(self, status: str) -> None:
        self.status = status
        if status == "approved":
            self.paid_at = self.paid_at or None
        elif status in {"paid", "settled"}:
            self.paid_at = datetime.now(UTC)
            self.payment_status = "settled"
            self._sync_commission_status()

    def set_payment_status(self, payment_status: str) -> None:
        self.payment_status = payment_status
        if payment_status == "settled":
            self.paid_at = datetime.now(UTC)
        self._sync_commission_status()

    def set_commission_enabled(self, enabled: bool, *, approved_by_management: bool | None = None) -> None:
        self.commission_enabled = enabled
        if approved_by_management is not None:
            self.commission_approved_by_management = approved_by_management
        self._sync_commission_status()

    def set_commission_approved(self, approved: bool) -> None:
        self.commission_approved_by_management = approved
        self._sync_commission_status()

    def _sync_commission_status(self) -> None:
        """Update commission_status based on payment_status, enablement, and approval."""
        self.commission_block_reason = None

        if not self.commission_enabled:
            self.commission_status = "none"
            self.commission_block_reason = "commission disabled"
            return

        if (self.initiator_type or "").lower() == "client" and not self.commission_approved_by_management:
            self.commission_status = "blocked"
            self.commission_block_reason = "management approval required for client-initiated commission"
            return

        if self.payment_status != "settled":
            self.commission_status = "pending"
            self.commission_block_reason = "awaiting payment settlement"
            return

        self.commission_status = "eligible"
        self.commission_block_reason = None

    @property
    def commission_amount(self) -> Decimal:
        if not self.commission_enabled:
            return Decimal("0.00")
        try:
            return (self.total_amount or Decimal("0")) * (self.commission_rate or Decimal("0"))
        except Exception:
            return Decimal("0.00")

    @staticmethod
    def valid_statuses() -> Iterable[str]:
        return (
            "submitted",
            "approved",
            "invoiced",
            "delivered",
            "paid",
            "settled",
            "pending",
            "shipped",
            "canceled",
            "rejected",
            "fulfilled",
        )

    def __repr__(self) -> str:
        return f"<Order {self.id} {self.status} {self.total_amount} {self.currency}>"




