ALTER DEFAULT PRIVILEGES FOR ROLE erp_user IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO erp_user;
ALTER DEFAULT PRIVILEGES FOR ROLE erp_user IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO erp_user;
