version: "3.8"
services:
  cache:
    image: redis:7-alpine
    command: ["redis-server","--save","","--appendonly","no"]
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  web:
    depends_on:
      db: { condition: service_healthy }
      cache: { condition: service_healthy }
    ports:
      - "18000:8000"
    environment:
      # make Limiter use Redis instead of in-memory
      PHASE1_LIMITER_STORAGE_URI: redis://cache:6379/0
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
