[build]
  command = "bash -lc 'echo No frontend build in Phase 1.1; exit 0'"
  publish = "netlify-blank"
  # Skip Netlify if no cached commit or FE didn?t change
  ignore = "bash -lc 'if [ -z \"$CACHED_COMMIT_REF\" ]; then exit 0; fi; git diff --quiet \"$CACHED_COMMIT_REF\" \"$COMMIT_REF\" -- web/** ui/** frontend/** package.json package-lock.json pnpm-lock.yaml yarn.lock'"