[build]
  # adjust these to your real frontend build if you have one
  command = "npm run build"
  publish = "dist"

  # Skip Netlify build when frontend files did NOT change.
  # Netlify ?ignore? command: exit 0 => skip; non-zero => run.
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- web/** ui/** frontend/** package.json package-lock.json pnpm-lock.yaml yarn.lock"