[project]
name = "your-project"
version = "0.1.0"
description = "Your app packaged by AI Overseer"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [{name="Your Name", email="you@example.com"}]
dependencies = []
[project.scripts]
your-cli = "your_package.cli:main"
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
