"""Module: celery_app.py — audit-added docstring. Refine with precise purpose when convenient."""
try:
    from celery import Celery
except Exception:
    Celery = None  # type: ignore

class _FakeTask:
    def __init__(self, f):
        """Lightweight task shim used when Celery is not installed."""

        self.f = f

    def delay(self, *a, **k):
        """Execute the wrapped function synchronously (Celery-less mode)."""

        return self.f(*a, **k)

    def __call__(self, *a, **k):
        """Execute the wrapped function synchronously (Celery-less mode)."""

        return self.f(*a, **k)

def make_celery(name="erp"):
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    if Celery is None:
        class _FakeCelery:
            def task(self, *dargs, **dkwargs):
                """Decorator shim that returns a synchronous _FakeTask wrapper."""

                def deco(f):
                    return _FakeTask(f)

                return deco

            def send_task(self, name: str, args=None, kwargs=None, **_opts):
                """Synchronously execute a task when Celery workers are unavailable."""

                import importlib

                module_name, _, func_name = name.rpartition(".")
                module = importlib.import_module(module_name)
                fn = getattr(module, func_name)
                return fn(*(args or ()), **(kwargs or {}))
        return _FakeCelery()
    app = Celery(name, broker="memory://", backend="rpc://")
    app.conf.task_always_eager = True
    return app

celery_app = make_celery()

