"""Module: celery_app.py — audit-added docstring. Refine with precise purpose when convenient."""
try:
    from celery import Celery
except Exception:
    Celery = None  # type: ignore

class _FakeTask:
    def __init__(self, f):
        """Autogenerated docstring (audit). Describe purpose, params, and return value."""
        self.f = f
    def delay(self, *a, **k):
        """Autogenerated docstring (audit). Describe purpose, params, and return value."""
        return self.f(*a, **k)
    def __call__(self, *a, **k):
        """Autogenerated docstring (audit). Describe purpose, params, and return value."""
        return self.f(*a, **k)

def make_celery(name="erp"):
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    if Celery is None:
        class _FakeCelery:
            def task(self, *dargs, **dkwargs):
                """Autogenerated docstring (audit). Describe purpose, params, and return value."""
                def deco(f): return _FakeTask(f)
                return deco
        return _FakeCelery()
    app = Celery(name, broker="memory://", backend="rpc://")
    app.conf.task_always_eager = True
    return app

celery_app = make_celery()

