"""Module: config.py — audit-added docstring. Refine with precise purpose when convenient."""

from __future__ import annotations
import os

class Config:
    DEBUG = os.getenv("FLASK_DEBUG", "0") == "1"
    TESTING = os.getenv("FLASK_TESTING", "0") == "1"
    SECRET_KEY = os.getenv("SECRET_KEY", "change-me-in-prod")
    DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///:memory:")
    SQLALCHEMY_DATABASE_URI = DATABASE_URL
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    CACHE_TYPE = os.getenv("CACHE_TYPE", "SimpleCache")
    CACHE_DEFAULT_TIMEOUT = int(os.getenv("CACHE_DEFAULT_TIMEOUT", 300))
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", "1") == "1"
    SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
    REMEMBER_COOKIE_HTTPONLY = True
    REMEMBER_COOKIE_SECURE = SESSION_COOKIE_SECURE
    REMEMBER_COOKIE_SAMESITE = SESSION_COOKIE_SAMESITE
    WTF_CSRF_TIME_LIMIT = int(os.getenv("WTF_CSRF_TIME_LIMIT", 3600))
    WTF_CSRF_CHECK_DEFAULT = True
    WTF_CSRF_HEADERS = ("X-CSRFToken", "X-CSRF-Token")
    JSON_LOGGING = os.getenv("JSON_LOGGING", "1") == "1"
    SENTRY_DSN = os.getenv("SENTRY_DSN")
    SENTRY_TRACES_SAMPLE_RATE = float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1"))
    SENTRY_ENVIRONMENT = os.getenv("SENTRY_ENVIRONMENT", os.getenv("FLASK_ENV", "production"))

def validate_config(cfg: Config):
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    is_prod = os.getenv("FLASK_ENV") == "production"
    if is_prod:
        if not cfg.SECRET_KEY or cfg.SECRET_KEY == "change-me-in-prod":
            raise RuntimeError("SECRET_KEY must be set in production")
        if not cfg.DATABASE_URL or cfg.DATABASE_URL.startswith("sqlite://"):
            raise RuntimeError("DATABASE_URL must be a real database in production")
# --- Flask-Security-Too defaults (override in env for prod)
SECURITY_PASSWORD_SALT = os.getenv("SECURITY_PASSWORD_SALT", "dev-not-secure")
SECURITY_PASSWORD_HASH = os.getenv("SECURITY_PASSWORD_HASH", "argon2")
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE  = True
SECURITY_TRACKABLE    = True
SECURITY_CONFIRMABLE  = False
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_USER_IDENTITY_ATTRIBUTES = ("email",)


