"""Module: context.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import current_app
from flask_wtf.csrf import generate_csrf

def register_context_processors(app):
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    @app.context_processor
    def inject_csrf():
        """Autogenerated docstring (audit). Describe purpose, params, and return value."""
        # Ensures {{ csrf_token() }} works in Jinja even without WTForms Form instance
        return {"csrf_token": generate_csrf}



