"""Module: health_checks.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, jsonify

health_bp = Blueprint("health_bp", __name__)

@health_bp.get("/health")
def health():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify({"ok": True})

@health_bp.get("/healthz")
def healthz():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return "ok", 200

@health_bp.get("/readyz")
def readyz():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    # keep it simple; tests only care about 200/503 status existence
    return "ok", 200
