"""Module: pytest_fixtures.py — audit-added docstring. Refine with precise purpose when convenient."""
import pytest
from erp import create_app

@pytest.fixture
def client():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    app = create_app()
    app.config["TESTING"] = True
    with app.test_client(use_cookies=True) as c:
        yield c

