"""Legacy banking UI wired to the shared banking models.

This module originally defined standalone ``BankAccount`` and ``BankStatement``
classes that collided with the upgraded banking models under
``erp.banking.models``.  To avoid metadata duplication (and the resulting
``InvalidRequestError: Table 'bank_accounts' is already defined``), we reuse the
central models and scope lookups by organisation via ``resolve_org_id``.
"""

from datetime import datetime
from decimal import Decimal
import csv, io

from flask import Blueprint, request, render_template, redirect, url_for, flash, jsonify
from flask_login import login_required

from erp.extensions import db
from erp.banking.models import BankAccount, BankStatement
from erp.utils import resolve_org_id

banking_bp = Blueprint("banking", __name__, url_prefix="/finance/banking", template_folder="../templates")

@banking_bp.route("/")
@login_required
def index():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return render_template("finance/banking/index.html")

@banking_bp.route("/upload", methods=["GET","POST"])
@login_required
def upload():
    """Legacy upload view: shortcut to new banking module."""
    flash(
        "Legacy banking UI is deprecated. Please use the new banking APIs for statements and reconciliation.",
        "warning",
    )
    return redirect(url_for("banking.index"))

@banking_bp.route("/reconcile", methods=["GET"])
@login_required
def reconcile():
    """Render legacy reconcile page with empty data to avoid schema drift."""
    return render_template("finance/banking/reconcile.html", txs=[])

@banking_bp.route("/api/unmatched", methods=["GET"])
@login_required
def api_unmatched():
    """API stub for unmatched transactions (legacy endpoint)."""
    return jsonify([])



