"""Module: views/main.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, render_template

bp = Blueprint("main", __name__)

@bp.get("/")
def index():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return render_template("index.html")



