apiVersion: batch/v1
kind: CronJob
metadata:
  name: erp-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: ghcr.io/getson7070/erp-berhan:latest
              command: ["python", "backup.py"]
              envFrom:
                - secretRef:
                    name: erp-secrets
