apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-berhan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: erp-berhan
  template:
    metadata:
      labels:
        app: erp-berhan
    spec:
      containers:
        - name: web
          image: erp-berhan:latest
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: erp-secrets
                  key: database_url
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: erp-secrets
                  key: flask_secret
            - name: DB_POOL_SIZE
              value: "10"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
