apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-berhan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: erp-berhan
  template:
    metadata:
      labels:
        app: erp-berhan
    spec:
      containers:
        - name: web
         iimage: 123456789012.dkr.ecr.eu-west-1.amazonaws.com/erp-berhan:latest
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: http
              ccontainerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: erp-secrets
                  key: database_url
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: erp-secrets
                  key: flask_secret
            - name: DB_POOL_SIZE
              value: "10"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /healthz
         port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
         port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: [erp-berhan]
              topologyKey: kubernetes.io/hostname
