apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: erp-berhan-pdb
spec:
  minAvailable: 2
  unhealthyPodEvictionPolicy: IfHealthyBudget
  selector:
    matchLabels:
      app: erp-berhan
