apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: erp
  labels:
    app: pgbouncer
data:
  pgbouncer.ini: |
    [databases]
    erp = host=postgres port=5432 dbname=erp
    [pgbouncer]
    max_client_conn = 100
    default_pool_size = 20
    pool_mode = transaction
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: erp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:1.23.0
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          args: ["pgbouncer", "/etc/pgbouncer/pgbouncer.ini"]
          ports:
            - containerPort: 5432
          readinessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 20
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /etc/pgbouncer
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
      volumes:
        - name: config
          configMap:
            name: pgbouncer-config
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: [pgbouncer]
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: erp
spec:
  selector:
    app: pgbouncer
  ports:
    - port: 5432
      targetPort: 5432
