"""User feedback collection endpoints."""

from flask import Blueprint, current_app, request, render_template

bp = Blueprint("feedback", __name__, url_prefix="/feedback")


@bp.get("/")
def form():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return render_template("feedback.html")


@bp.post("/")
def submit():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    data = request.get_json() or {}
    current_app.logger.info("user_feedback", extra={"feedback": data})
    return ("", 204)


