"""Module: routes/finance.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, jsonify

finance_api_bp = Blueprint("finance_api", __name__, url_prefix="/api/finance")

@finance_api_bp.get("/health")
def health():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify({"ok": True})

bp = finance_api_bp

