"""Module: routes/help.py — audit-added docstring. Refine with precise purpose when convenient."""
from __future__ import annotations
from flask import Blueprint, render_template, Response

bp = Blueprint("help", __name__)
@bp.get("/help")
def help():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    try:
        return render_template("help.html")
    except Exception:
        return Response("<html><body><h1>Help</h1></body></html>", mimetype="text/html")
@bp.get("/offline")
def offline():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return Response("<html><body>The application is offline</body></html>", mimetype="text/html")



