"""Module: routes/misc.py — audit-added docstring. Refine with precise purpose when convenient."""
from __future__ import annotations
from flask import Blueprint, jsonify
from erp.utils import idempotent

bp = Blueprint("misc", __name__)

@bp.post("/idem")
@idempotent
def idem():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify({"status": "ok"})



