"""Module: routes/plugins_sample.py — audit-added docstring. Refine with precise purpose when convenient."""
from __future__ import annotations
from flask import Blueprint, Response
bp = Blueprint("plugins_sample", __name__, url_prefix="/plugins/sample")
@bp.get("/")
def index():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return Response("ok", mimetype="text/plain")



