services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U erp -d erp"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://erp:erp@db:5432/erp
      FLASK_LIMITER_STORAGE_URI: redis://redis:6379/0
      PYTHONUNBUFFERED: "1"
    # run migrations, then start gunicorn
    command: ["/bin/sh","-lc","alembic -c alembic.ini upgrade head && exec gunicorn -b 0.0.0.0:8000 deploy.wsgi:app"]
    ports:
      - "18000:8000"