-- Creates a dedicated application role. Provide APP_DB_PASSWORD via environment.
CREATE USER erp_app WITH PASSWORD '${APP_DB_PASSWORD}';
CREATE DATABASE erp;
GRANT CONNECT ON DATABASE erp TO erp_app;
\c erp
GRANT USAGE ON SCHEMA public TO erp_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO erp_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO erp_app;
