"""init schema clean

revision = "59764003235d"
down_revision = 'b387fb58b4db'
branch_labels = None
depends_on = None
Create Date: 2025-11-04 21:30:09.818936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59764003235d'
down_revision = 'b387fb58b4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
