"""sync models (probe)

Revision ID: aadafacb7a37
Revises: prep_20251029_120526
Create Date: 2025-10-29 22:43:35.271409
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'aadafacb7a37'
down_revision = 'prep_20251029_120526'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('ix_idem_created_at', table_name='idempotency_keys')
    op.drop_index('ix_idem_endpoint', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('trusted_devices')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_devices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('device_fingerprint', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ua', sa.VARCHAR(length=512), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('issued_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_fingerprint', name='uq_user_device')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=128), nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_idem_key')
    )
    op.create_index('ix_idem_endpoint', 'idempotency_keys', ['endpoint'], unique=False)
    op.create_index('ix_idem_created_at', 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
