"""feat: add finance/integration/recall tables

Revision ID: f38a77f2570a
Revises: 0001_initial_core
Create Date: 2025-10-17 17:04:42.993128
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f38a77f2570a'
down_revision = '0001_initial_core'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# REMOVED: op.drop_table("users")
    # ### end Alembic commands ###

def downgrade():
    pass

