"""Module: sales/routes.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, jsonify
from .models import SalesOrder  # noqa: F401

bp = Blueprint("sales", __name__)


@bp.get("/sales/health")
def health():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify({"ok": True})



