"""Module: blueprints/finance.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, jsonify

finance_bp = Blueprint("finance", __name__, url_prefix="/finance")

@finance_bp.get("/health")
def health():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify({"ok": True})

bp = finance_bp
