"""Module: blueprints/health_compat.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, jsonify

bp = Blueprint("health_compat", __name__)

@bp.get("/health")
def health():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify(ok=True)

@bp.get("/healthz")
def healthz():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify(ok=True)

