"""Module: blueprints/health.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, jsonify

bp = Blueprint("health", __name__)

@bp.get("/health/ready")
def ready():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    # Keep tiny; do not hit DB here unless you truly need it
    return jsonify(status="ready")

@bp.get("/health/live")
def live():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify(status="live")

bp = health_bp
