"""Module: blueprints/login_ui.py — audit-added docstring. Refine with precise purpose when convenient."""
# erp/blueprints/login_ui.py
from flask import Blueprint, render_template
bp = Blueprint("login_ui", __name__)

@bp.get("/login")
def login():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return render_template("login.html")

