"""Module: blueprints/telegram_webhook.py — audit-added docstring. Refine with precise purpose when convenient."""
# erp/blueprints/telegram_webhook.py
import os

try:
    import requests
except Exception:  # pragma: no cover - optional dependency in tests
    requests = None  # type: ignore

from flask import Blueprint, current_app, jsonify, request

from erp.bot_security import verify_telegram_secret
from erp.extensions import limiter
bp = Blueprint("telegram_webhook", __name__, url_prefix="/bot/telegram")

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
ALLOWED_IDS = {int(x) for x in os.getenv("TELEGRAM_ALLOWED_USER_IDS","").split(",") if x.strip().isdigit()}

def send_message(chat_id: int, text: str):
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    if not BOT_TOKEN or requests is None:
        return
    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    requests.post(url, json={"chat_id": chat_id, "text": text})

@bp.post("/webhook")
@limiter.limit("15/minute")
def webhook():
    """Telegram webhook guarded by shared secret and allowlist."""

    if not BOT_TOKEN:
        return jsonify({"ok": False, "error": "bot not configured"}), 400

    if not verify_telegram_secret(request):
        current_app.logger.warning("Rejected Telegram webhook due to missing secret")
        return jsonify({"ok": False, "error": "unauthorized"}), 401

    update = request.get_json(force=True, silent=True) or {}
    msg = (update.get("message") or {})
    chat = msg.get("chat") or {}
    user = msg.get("from") or {}
    chat_id = chat.get("id")
    user_id = user.get("id")
    if user_id not in ALLOWED_IDS:
        send_message(chat_id, "Access denied.")
        return jsonify({"ok": True})
    text = (msg.get("text") or "").strip().lower()
    if text in ("/start","help"):
        send_message(chat_id, "Hello. Your access is confirmed.")
    elif text == "health":
        send_message(chat_id, "OK")
    else:
        send_message(chat_id, f"Echo: {text}")
    return jsonify({"ok": True})

