"""Module: observability/diagnostics.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, current_app, render_template, jsonify

diagnostics_bp = Blueprint("diagnostics", __name__, template_folder="../templates")

@diagnostics_bp.get("/diagnostics")
def diagnostics():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    failures = current_app.config.get("IMPORT_FAILURES", [])
    bps = current_app.config.get("REGISTERED_BLUEPRINTS", [])
    return render_template("admin/diagnostics.html", failures=failures, blueprints=bps)

@diagnostics_bp.get("/blueprints")
def blueprints():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify(current_app.config.get("REGISTERED_BLUEPRINTS", []))

@diagnostics_bp.get("/import_failures")
def import_failures():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify(current_app.config.get("IMPORT_FAILURES", []))



