"""Module: procurment/routes.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, jsonify
from .models import PurchaseOrder  # noqa: F401

bp = Blueprint("procurment", __name__)


@bp.get("/procurment/health")
def health():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify({"ok": True})



