"""Module: auth/mfa_routes.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, jsonify

bp = Blueprint("mfa", __name__)

@bp.get("/ping")
def ping():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify({"ok": True, "module": "mfa"}), 200

