"""Module: ops/status.py — audit-added docstring. Refine with precise purpose when convenient."""
from flask import Blueprint, jsonify

bp = Blueprint("status", __name__)

@bp.get("/healthz")
def healthz():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify({"ok": True, "service": "erp"}), 200

@bp.get("/health")
def health():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    return jsonify({"ok": True, "service": "erp"}), 200

