"""Module: scripts/seed_accounts.py — audit-added docstring. Refine with precise purpose when convenient."""
from datetime import UTC, datetime
from werkzeug.security import generate_password_hash

from flask import current_app
from erp.app import create_app  # change if your factory path differs

def _db():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    try:
        return current_app.extensions['sqlalchemy'].db
    except Exception:
        from erp.extensions import db  # type: ignore
        return db

def ensure_role(db, name: str):
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    Role = db.Model._decl_class_registry.get('Role')  # dynamic
    r = db.session.query(Role).filter_by(name=name).first()
    if not r:
        r = Role(name=name)
        db.session.add(r); db.session.commit()
    return r

def ensure_user(db, email: str, password: str, role_name: str):
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    User = db.Model._decl_class_registry.get('User')
    u = db.session.query(User).filter_by(email=email).first()
    if not u:
        role = ensure_role(db, role_name)
        u = User(email=email, password_hash=generate_password_hash(password), role_id=role.id, is_active=True, created_at=datetime.now(UTC))
        db.session.add(u); db.session.commit()
    return u

def main():
    """Autogenerated docstring (audit). Describe purpose, params, and return value."""
    app = create_app()
    with app.app_context():
        db = _db()
        ensure_user(db, "admin@local.test", "Dev!23456", "admin")
        ensure_user(db, "emp1@local.test", "Pass!12345", "employee")
        ensure_user(db, "client1@local.test", "Pass!12345", "client")
        print("Seeded admin/employee/client")

if __name__ == "__main__":
    main()

