"""Freeze current blueprint registry into a curated allowlist file.

Usage:
    python -m erp.tools.freeze_blueprints
Produces:
    erp/blueprints_explicit.py  with ALLOWLIST = [("import.path","/prefix"), ...]
"""
import json, os, sys, re
from importlib import import_module
from flask import Flask

from erp import create_app

def main():
    app = create_app()
    with app.app_context():
        allow = []
        for name, bp in app.blueprints.items():
            mod = getattr(bp, 'import_name', None) or ''
            # try to normalize module path to package.module
            if mod and ':' in mod:
                mod = mod.split(':')[0]
            # try to guess module name holding `bp`
            import_path = mod if mod else f"<unknown:{name}>"
            prefix = bp.url_prefix or '/'
            allow.append((import_path, prefix))
        os.makedirs("erp", exist_ok=True)
        out = os.path.join("erp","blueprints_explicit.py")
        with open(out, "w", encoding="utf-8") as f:
            f.write("# Auto-generated by freeze_blueprints; review and curate for PROD\n")
            f.write("ALLOWLIST = [\n")
            for mod, pref in allow:
                f.write(f"    (\"{mod}\", \"{pref}\"),\n")
            f.write("]\n")
        print(f"Wrote {out} with {len(allow)} entries")

if __name__ == "__main__":
    main()
