name: Accessibility
on: [push, pull_request]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm i -g pa11y
      - name: Pa11y smoke
        run: |
          # replace with your key pages or local server URL in preview
          pa11y https://example.com --threshold 5 || true
