name: Alembic single-head check
on:
  pull_request:
  push:
jobs:
  invariant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install "alembic==1.13.*" "SQLAlchemy==2.*"
      - name: Check single head(s)
        run: python scripts/check_alembic_single_head.py