name: Alembic one-head invariant
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  invariant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: pip install -r requirements.txt
      - name: Enforce single head
        run: |
          COUNT=$(alembic -c alembic.ini heads -q | wc -w | tr -d ' ')
          echo "Heads: $COUNT"
          if [ "$COUNT" -ne 1 ]; then
            echo "::error ::Expected exactly 1 Alembic head, found $COUNT"
            exit 1
          fi
