name: Alembic single-head check

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  alembic-heads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install alembic
        run: |
          python -m pip install --upgrade pip
          pip install alembic

      - name: Verify single migration head
        run: |
          python scripts/check_alembic_single_head.py
