name: CI - Phase 1

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: erp
          POSTGRES_PASSWORD: erp
          POSTGRES_DB: erp
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U erp"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=10
      redis:
        image: redis:7
        ports: ["6379:6379"]

    env:
      DATABASE_URL: postgresql+psycopg2://erp:erp@localhost:5432/erp
      REDIS_URL: redis://localhost:6379/0
      SECRET_KEY: test-secret
      FLASK_ENV: testing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-phase1.txt

      - name: Wait for Postgres
        run: python tools/ci/wait_for_service.py localhost 5432

      - name: Wait for Redis
        run: python tools/ci/wait_for_service.py localhost 6379

      - name: Run tests
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: 1
        run: |
          pytest -c tests/ci-min.ini

      - name: Enforce single Alembic head (if present)
        run: bash tools/ci/check_alembic_single_head.sh

