name: Dependabot auto-merge (security patch/minor)

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Label PR for visibility
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            dependencies
            security

      - name: Attempt auto-approve
        if: steps.meta.outputs.update-type == 'version-update:semver-patch' || steps.meta.outputs.update-type == 'version-update:semver-minor'
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-merge@v3
        with:
          merge-method: squash

      - name: Auto-merge when ready
        if: |
          (steps.meta.outputs.update-type == 'version-update:semver-patch' || steps.meta.outputs.update-type == 'version-update:semver-minor') &&
          (steps.meta.outputs.dependency-type == 'direct:production' || steps.meta.outputs.security-advisory-ghsa-id != '')
        uses: peter-evans/auto-merge@v3
        with:
          merge-method: squash
