name: Migrations Check
on:
  pull_request:
  push:
permissions:
  contents: read
jobs:
  alembic-heads:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Migrations Check muted (legacy head check replaced elsewhere)."