name: Post-Deploy Smoke

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL of deployed app (e.g., https://your-app.onrender.com)'
        required: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip requests
      - name: Run smoke suite
        env:
          SMOKE_BASE_URL: ${{ github.event.inputs.base_url }}
        run: python scripts/smoke/post_deploy_smoke.py
