name: predeploy-gates
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  gates:
    runs-on: ubuntu-latest
    env:
      PREDEPLOY_STRICT: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (best-effort)
        run: |
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
          if [ -f requirements-optional.txt ]; then pip install -r requirements-optional.txt || true; fi
      - name: Run predeploy gates (strict)
        run: python scripts/ci/run_predeploy_gates.py
