name: Security Scan
on:
  pull_request:
  push:
permissions:
  contents: read
jobs:
  deps-secrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Security Scan muted (use Gitleaks job instead)."