name: security-gates
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
permissions:
  contents: read
  security-events: write
  actions: read
jobs:
  gitleaks:
    name: Secret scanning (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: "true"

  dependency-review:
    name: Dependency review (GH native)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          # Block high & critical
          fail-on-severity: high

  pip-audit:
    name: Python vulnerability audit (pip-audit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit==2.7.3
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
      - name: Run pip-audit
        run: |
          pip-audit -r requirements.txt --strict --ignore-vuln GHSA-xxxx-xxxx-xxxx || exit 1
