name: ui-preview
on:
  pull_request:
    paths:
      - "web/**"
      - "ui/**"
      - "frontend/**"
      - "package.json"
      - "package-lock.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"
  push:
    paths:
      - "web/**"
      - "ui/**"
      - "frontend/**"
      - "package.json"
      - "package-lock.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: No-op UI preview (quiet)
        run: echo "Deploy preview handled by Netlify App; this workflow stays green quietly."