name: Verify Signed Commits

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Verify commit signatures
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          BASE: ${{ github.event.pull_request.base.sha }}
          HEAD: ${{ github.event.pull_request.head.sha }}
        run: |
          for sha in $(git rev-list $BASE..$HEAD); do
            verified=$(curl -s -H "Authorization: Bearer $TOKEN" https://api.github.com/repos/$REPO/commits/$sha | jq -r '.commit.verification.verified')
            if [ "$verified" != "true" ]; then
              echo "Commit $sha is not signed" >&2
              exit 1
            fi
          done
