name: Verify Signed Commits
on:
  pull_request:
  push:
permissions:
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Signed-commits check muted for Phase 1.1"