name: visual

on:
  pull_request:
    paths:
      - "templates/**"
      - "static/**"
      - "frontend/**"
      - "package.json"
      - "package-lock.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"
      - "playwright.config.*"
      - "tests/visual/**"
      - "e2e/**"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  visual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Probe for a JS/visual test setup; skip cleanly if not present
      - name: Probe for visual test setup
        id: probe
        shell: bash
        run: |
          set -euo pipefail
          has_pkg=false; has_playwright=false; has_tests=false
          [[ -f package.json ]] && has_pkg=true
          [[ -f playwright.config.ts || -f playwright.config.js || -f playwright.config.mjs ]] && has_playwright=true
          [[ -d tests/visual || -d e2e ]] && has_tests=true
          echo "has_pkg=$has_pkg"           >> $GITHUB_OUTPUT
          echo "has_playwright=$has_playwright" >> $GITHUB_OUTPUT
          echo "has_tests=$has_tests"       >> $GITHUB_OUTPUT

      - name: Skip (no visual tests in repo)
        if: steps.probe.outputs.has_pkg == 'false' || (steps.probe.outputs.has_playwright == 'false' && steps.probe.outputs.has_tests == 'false')
        run: |
          echo "No visual test setup detected. Skipping."
          echo "To enable: add package.json + Playwright config + tests/visual or e2e/"
          exit 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json','**/pnpm-lock.yaml','**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile
          elif [ -f yarn.lock ]; then
            yarn --frozen-lockfile
          else
            npm ci
          fi

      - name: Install Playwright (with browsers)
        run: npx playwright install --with-deps

      - name: Run visual tests
        run: npx playwright test --reporter=line

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
