name: visual
on:
  pull_request:
    paths:
      - "web/**"
      - "ui/**"
      - "frontend/**"
      - "package.json"
      - "package-lock.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"
  push:
    paths:
      - "web/**"
      - "ui/**"
      - "frontend/**"
      - "package.json"
      - "package-lock.json"
      - "pnpm-lock.yaml"
      - "yarn.lock"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  visual:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: No-op visual regression (quiet)
        run: echo "Visual diffs silenced. Hook your real tool here later."